version: "3.9"

services:
    flask:
        build: "./backend"
        container_name: flask
        restart: unless-stopped
        environment:
            MONGODB_URI_STRING: mongodb://mongodbuser:mongodbpassword@mongodb:27017/flaskdb?authSource=admin
        ports:
            - 5050:5000
        volumes:
            - ./backend/app:/usr/app
        depends_on:
            - mongodb
        networks:
            - backend

    mongodb:
        image: mongo:4.0.8
        container_name: mongodb
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodbuser
            MONGO_INITDB_ROOT_PASSWORD: mongodbpassword
        ports:
            - '27017:27017'
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

volumes:
    mongodbdata:
        driver: local

networks:
    backend:
        driver: bridge
